name: Pull Request Checks
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: '22.x'
            cache: 'npm'
        - run: npm install

        - run: npx eslint --quiet
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: '22.x'
            cache: 'npm'
        - run: npm install

        - name: cache card data json files
          id: cache-card-data
          uses: actions/cache@v3
          with:
            path: ./test/json
            key: sor-shd-manual-v04-specialchars
        - if: ${{ steps.cache-card-data.outputs.cache-hit != 'true' }}
          run: npm run get-cards

        # TODO: figure out why test-parallel gives weird error on test failure
        - run: npm test